2017-07-08T09:31:17.8939632-05:00  [INF] User profile is available. Using '"C:\Users\boneill\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest. (7ac5e29c)
2017-07-08T09:31:18.1907170-05:00 0HL661NVGO3J5 [INF] Request starting HTTP/1.1 GET http://localhost:2228/   (e5be5b71)
2017-07-08T09:31:18.7672825-05:00 0HL661NVGO3J5 [INF] Executing action method "SecretSantaApp.Controllers.HomeController.Index (SecretSantaApp)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-07-08T09:31:19.9704502-05:00 0HL661NVGO3J5 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2017-07-08T09:31:20.5499918-05:00 0HL661NVGO3J5 [INF] Executed action "SecretSantaApp.Controllers.HomeController.Index (SecretSantaApp)" in 1932.6082ms (afa2e885)
2017-07-08T09:31:20.6482795-05:00 0HL661NVGO3J5 [INF] Request finished in 2475.2631ms 200 text/html; charset=utf-8 (15c52c40)
2017-07-08T09:31:20.6933733-05:00 0HL661NVGO3J6 [INF] Request starting HTTP/1.1 GET http://localhost:2228/lib/bootstrap/dist/css/bootstrap.css   (e5be5b71)
2017-07-08T09:31:20.6933733-05:00 0HL661NVGO3J7 [INF] Request starting HTTP/1.1 GET http://localhost:2228/css/site.css   (e5be5b71)
2017-07-08T09:31:20.6983864-05:00 0HL661NVGO3J8 [INF] Request starting HTTP/1.1 GET http://localhost:2228/lib/bootstrap/dist/js/bootstrap.js   (e5be5b71)
2017-07-08T09:31:20.6983864-05:00 0HL661NVGO3J9 [INF] Request starting HTTP/1.1 GET http://localhost:2228/js/modal.js   (e5be5b71)
2017-07-08T09:31:20.6993897-05:00 0HL661NVGO3JA [INF] Request starting HTTP/1.1 GET http://localhost:2228/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.js   (e5be5b71)
2017-07-08T09:31:20.7134262-05:00 0HL661NVGO3J9 [INF] The file "/js/modal.js" was not modified (f1f8d725)
2017-07-08T09:31:20.7134262-05:00 0HL661NVGO3JA [INF] The file "/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.js" was not modified (f1f8d725)
2017-07-08T09:31:20.7144287-05:00 0HL661NVGO3J7 [INF] The file "/css/site.css" was not modified (f1f8d725)
2017-07-08T09:31:20.7144287-05:00 0HL661NVGO3J8 [INF] The file "/lib/bootstrap/dist/js/bootstrap.js" was not modified (f1f8d725)
2017-07-08T09:31:20.7144287-05:00 0HL661NVGO3J6 [INF] The file "/lib/bootstrap/dist/css/bootstrap.css" was not modified (f1f8d725)
2017-07-08T09:31:20.7204477-05:00 0HL661NVGO3J9 [INF] Request finished in 21.712ms 304 application/javascript (15c52c40)
2017-07-08T09:31:20.7204477-05:00 0HL661NVGO3J8 [INF] Request finished in 22.5804ms 304 application/javascript (15c52c40)
2017-07-08T09:31:20.7204477-05:00 0HL661NVGO3JA [INF] Request finished in 20.9066ms 304 application/javascript (15c52c40)
2017-07-08T09:31:20.7204477-05:00 0HL661NVGO3J6 [INF] Request finished in 27.4769ms 304 text/css (15c52c40)
2017-07-08T09:31:20.7204477-05:00 0HL661NVGO3J7 [INF] Request finished in 27.1499ms 304 text/css (15c52c40)
2017-07-08T09:31:31.1523487-05:00 0HL661NVGO3JB [INF] Request starting HTTP/1.1 GET http://localhost:2228/Groups   (e5be5b71)
2017-07-08T09:31:31.1704194-05:00 0HL661NVGO3JB [INF] Authorization failed for user: null. (a4ab1676)
2017-07-08T09:31:31.1714222-05:00 0HL661NVGO3JB [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2017-07-08T09:31:31.1744066-05:00 0HL661NVGO3JB [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2017-07-08T09:31:31.1934873-05:00 0HL661NVGO3JB [INF] AuthenticationScheme: "Cookies" was challenged. (d45f1f38)
2017-07-08T09:31:31.1934873-05:00 0HL661NVGO3JB [INF] Executed action "SecretSantaApp.Controllers.GroupsController.Index (SecretSantaApp)" in 37.5768ms (afa2e885)
2017-07-08T09:31:31.1944603-05:00 0HL661NVGO3JB [INF] Request finished in 41.6902ms 302  (15c52c40)
2017-07-08T09:31:31.1994848-05:00 0HL661NVGO3JC [INF] Request starting HTTP/1.1 GET http://localhost:2228/Account/LoginExternal?ReturnUrl=%2FGroups   (e5be5b71)
2017-07-08T09:31:31.2756754-05:00 0HL661NVGO3JC [INF] Executing action method "SecretSantaApp.Controllers.AccountController.LoginExternal (SecretSantaApp)" with arguments (["", "/Groups"]) - ModelState is Valid (ba7f4ac2)
2017-07-08T09:31:31.2776834-05:00 0HL661NVGO3JC [INF] Executing ChallengeResult with authentication schemes (["Auth0"]). (f3dca807)
2017-07-08T09:31:31.3288479-05:00 0HL661NVGO3JC [INF] Executed action "SecretSantaApp.Controllers.AccountController.LoginExternal (SecretSantaApp)" in 128.2386ms (afa2e885)
2017-07-08T09:31:31.3559200-05:00 0HL661NVGO3JC [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'https://bplus0.auth0.com/.well-known/openid-configuration'. ---> System.IO.IOException: IDX10804: Unable to retrieve document from: 'https://bplus0.auth0.com/.well-known/openid-configuration'. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server name or address could not be resolved
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.<GetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleUnauthorizedAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<ChallengeAsync>d__72.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<ChallengeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.<ExecuteResultAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware.<ExecuteWithFilter>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-07-08T09:31:31.5022791-05:00 0HL661NVGO3JC [INF] Request finished in 303.2953ms 500 text/html; charset=utf-8 (15c52c40)
2017-07-08T09:32:57.6828339-05:00 0HL661NVGO3JD [INF] Request starting HTTP/1.1 GET http://localhost:2228/Account/LoginExternal   (e5be5b71)
2017-07-08T09:32:57.6853399-05:00 0HL661NVGO3JD [INF] Executing action method "SecretSantaApp.Controllers.AccountController.LoginExternal (SecretSantaApp)" with arguments (["", "/"]) - ModelState is Valid (ba7f4ac2)
2017-07-08T09:32:57.6858628-05:00 0HL661NVGO3JD [INF] Executing ChallengeResult with authentication schemes (["Auth0"]). (f3dca807)
2017-07-08T09:32:58.4437129-05:00 0HL661NVGO3JD [INF] AuthenticationScheme: "Auth0" was challenged. (d45f1f38)
2017-07-08T09:32:58.4437129-05:00 0HL661NVGO3JD [INF] Executed action "SecretSantaApp.Controllers.AccountController.LoginExternal (SecretSantaApp)" in 758.5259ms (afa2e885)
2017-07-08T09:32:58.4442170-05:00 0HL661NVGO3JD [INF] Request finished in 761.6334ms 302  (15c52c40)
